site_name: Unglue Workflow
nav:
  - About: 'index.md'
  - Start: 'start.md'
  - Client: 'client.md'
  - Server: 'server.md'
theme:
  name: 'readthedocs'
nav:
    - About: index.md
    - Start: start.md
    - Client: client.md
    - Server: server.md